version: '3'
services:
  clicky-game:
    build: .
    ports:
     - "3000:3000"
     - "35729:35729"
     - "9229:9229"
    volumes:
     - .:/usr/src/app
    environment:
     - NODE_ENV=development
     - CHOKIDAR_USEPOLLING=true